#!/bin/bash
# Script to setup my Working Environment.
# Sriharsha Sukumar Mucheli : harshasrisri@gmail.com

if [ ! -x dotRC ]; then echo "Change to dotRC Directory first"; exit; fi

BackupDir="$PWD/.dotRC_Backup"

setup() {
	files=( ~/.bashrc ~/.bash_logout ~/.vim ~/.vimrc )

	echo -n "Back up start..."
	mkdir -p $BackupDir
	for i in ${files[*]}; do
		if [ -e $i ]; then
			echo -n "$i "
			mv $i $BackupDir
		fi
	done
	echo "... Done!"

	ln -sf $PWD/bash/bashrc ~/.bashrc
	ln -sf $PWD/bash/bash_logout ~/.bash_logout
	ln -sf $PWD/vim ~/.vim
	ln -sf $PWD/vim/vimrc ~/.vimrc

	mkdir -p vim/autoload vim/bundle

	echo -n "Pathogen setup... "
	git clone --quiet http://github.com/tpope/vim-pathogen vim/Pathogen
	mv vim/Pathogen/autoload/pathogen.vim vim/autoload/ --force
	rm --recursive --force vim/Pathogen
	echo "Done!"

	echo -n "Submodule setup "
	while IFS= read <&3 line || [ -n "$line" ];
	do
		echo -n ". "
		git submodule add --quiet --force $line &> /dev/null
		git submodule init && git submodule update
	done 3< vim/plugin_list
	echo "Done!"
	
	. ~/.bashrc
	echo "All set to go!"
}

reset() {
	if [ ! -e $BackupDir ]; then
		echo "Backup directory not present!!"
		exit
	fi

	shopt -s dotglob
	if [ -h ~/.vim ]; then rm ~/.vim; fi
	mv $BackupDir/* ~/
	rm -rf $BackupDir
	echo "Reset Complete. Back to your old Setup!"
}

update() {
	git pull
	git submodule foreach git pull
}

case $1 in
	setup ) setup
		;;
	reset ) reset
		;;
	update ) update
		;;
	* ) echo "Usage : ./dotRC [setup | reset | update]"
		;;
esac
