alias ll='ls --color=auto -lFht'
alias lla='ls --color=auto -lFhta'
alias la='ls --color=auto -a'
alias lr='ls --color=auto -R'
alias l='ls --color=auto -CF'
alias ls='ls --color=auto -CF'
alias l.='ls  --color=auto -d .*'
alias ..='cd ..; ls'
alias .b='vi ~/.bashrc'
alias .v='vi ~/.vimrc'
alias .z='vi ~/.zshrc'
alias ..b='. ~/.bashrc'
alias ..z='. ~/.zshrc'
alias x='exit'
alias wget='wget -c'
alias grep='grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn'
alias pgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias scpnoverify="scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias sshnoverify="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

alias ga='git add'
alias gpu='git push'
alias gpl='git pull'
alias gcl='git clone'
alias gl='git log --oneline --decorate --date=short --graph'
alias gs='git status'
alias gd='git diff'
alias gdt='git difftool'
alias gdc='git diff --cached'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gbr='git branch'
alias gco='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
