## git related stuff
alias ga='git add'
alias gpu='git push'
alias gpl='git pull'
alias gcl='git clone'
alias gl='git log --oneline --decorate --date=short --graph'
alias gs='git status'
alias gd='git diff'
alias gdt='git difftool'
alias gdc='git diff --cached'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gbr='git branch'
alias gco='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
