call plug#begin('~/.vim/plugins')
"" Eye Candy
Plug 'altercation/vim-colors-solarized'
Plug 'itchyny/lightline.vim'
Plug 'mengelbrecht/lightline-bufferline'

"" Common Utilities
Plug 'junegunn/vim-peekaboo'
Plug 'junegunn/fzf', { 'dir': '~/.vim/fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'wincent/ferret'
Plug 'godlygeek/tabular', {'on' : 'Tab'}
Plug 'tpope/vim-fugitive'

"" Common Programming Utilities
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'cohama/lexima.vim'
Plug 'chaoren/vim-wordmotion'
Plug 'Yggdroot/indentLine'
Plug 'lifepillar/vim-mucomplete'
Plug 'majutsushi/tagbar', {'on' : 'TagbarToggle'}

"" C/C++ specific Utilities
Plug 'vim-scripts/fly.vim', {'on' : 'SW' }
Plug 'basilgor/vim-autotags'

"" Rust specific Utilities
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'bash install.sh'}
call plug#end()

"" Initializations
    set nocompatible                       " No comatibility with old Vi
    set ruler                              " Display line info in status line
    set number                             " Display line numbers on the left side
    set hidden                             " Hide closed buffers instead of closing them.
    set cursorline                         " Horizontal line to indicate cursor
    set wildmenu                           " Pressing tab in command mode shows options on status bar
    set noshowmode                         " Don't show mode on command line
    set splitbelow                         " Open a new split below the current one
    set splitright                         " Open a new vertical split to the right of the current one
    set autoread                           " Auto reload files changed outside vim
    set colorcolumn=80                     " 80-column marker
    set scrolloff=5                        " Number of lines to keep at the top and bottom of a window while scrolling
    set updatetime=500                     " Time interval to update windows
    set laststatus=2                       " Display Statusbar always.
    set showtabline=2                      " Display tabline always.
    set backspace=indent,eol,start         " Backspace works over whitespaces also
    set formatoptions+=jcron               " Join lines works well with comments
    set tags=tags;                         " Set vim to look for tags file recursively upwards
    set pastetoggle=<F2>                   " Toggle prevent unnecessary autoindent on mouse click paste
    set mouse=a                            " Enable Mouse in all modes
    set tabstop=4                          " Show a tabstop as 4 spaces
    set shiftwidth=4                       " Auto indent shifts 4 spaces
    set expandtab                          " Insert 4 spaces when Tab is pressed
    set incsearch                          " Incremental Search
    set hlsearch                           " Highlight searches
    set smartcase                          " Ignore case if searching lowercase, not otherwise
    set directory=~/.vim/tempfiles/        " Central directory for swap files
    set backupdir=~/.vim/tempfiles/        " Central directory for backup files
    set undodir=~/.vim/tempfiles/          " Central directory for file undo history
    set undofile                           " Remember undo history for closed files
    set t_Co=256                           " Set terminal to 256 colors
    set background=dark                    " Set dark colorschemes

    syntax on                              " Enable syntax highlighting
    filetype plugin indent on              " Enable Filetype indent plugin
    silent! colorscheme solarized          " Set colorscheme to Solarized-dark
    let g:solarized_termtrans=1            " Adjusts to terminal colors by itself
    let mapleader="\<Space>"               " For setting the leader

    "" Vim jumps to the last known position when reopening a file
    au! BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

    " Apply .vimrc on the fly after saving
    au! bufwritepost .vimrc source $MYVIMRC

"" Copy-Paste-Fu
    " Cut/Copy/Replace selection to clipboard in visual mode
    vnoremap <leader>d "+d
    vnoremap <leader>y "+y
    vnoremap <leader>p "+p
    vnoremap <leader>P "+P
    " Paste from clipboard before/after position in normal mode
    nnoremap <leader>P "+P
    nnoremap <leader>p "+p
    " Place cursor after copy/paste position in Normal/Visual mode
    vnoremap <silent> y y`]
    vnoremap <silent> p p`]
    nnoremap <silent> p p`]

"" Navigation mappings
    " Go between lines in wrapped lines.
    nnoremap j gj
    nnoremap k gk

    " Buffer movements
    nnoremap <C-n> :bnext<CR>
    nnoremap <C-p> :bprevious<CR>
    nnoremap <leader>b :Buffers<CR>
    nnoremap <leader>f :Files<CR>

    " Maps Ctrl+[h,j,k,l] to move between window splits
    nnoremap <leader>h <C-w>h
    nnoremap <leader>j <C-w>j
    nnoremap <leader>k <C-w>k
    nnoremap <leader>l <C-w>l

    " Maps Ctrl+arrow keys to resize the window splits
    nnoremap <C-h> <C-w>< 
    nnoremap <C-j> <C-W>-
    nnoremap <C-k> <C-W>+
    nnoremap <C-l> <C-w>>

"" Miscellaneous
    " Easy save as sudo
    cnoremap w!! w !sudo tee %

    " Opens help in a vertical split rather than horizontal
    cnoremap vh vert help

    "" Easy <ESC> in INSERT mode
    inoremap jj <Esc>

"" Autotags Settings
    nmap <leader>au :call AutotagsUpdate()<CR>
    let g:autotags_pathhash_humanreadable = 1
    let g:autotags_ctags_exe = "echo"
    let g:autotags_ctags_opts = ""

"" Lightline+Bufferline settings
    let g:lightline#bufferline#unnamed = '[new]'
    let g:lightline#bufferline#show_number = 1
    let g:lightline = {
        \ 'colorscheme': 'deus',
        \ 'component': { 'lineinfo': ' %3l:%-2v' },
        \ 'separator': { 'left': '', 'right': '' },
        \ 'subseparator': { 'left': '', 'right': '' },
        \ 'component_function': {
        \     'readonly': 'LightlineReadonly',
        \     'fugitive': 'LightlineFugitive'
        \   },
        \ 'tabline': { 'left': [['buffers']], 'right': [['close']] },
        \ 'component_expand': { 'buffers': 'lightline#bufferline#buffers' },
        \ 'component_type': { 'buffers': 'tabsel', },
        \ }

    function! LightlineReadonly()
        return &readonly ? '' : ''
    endfunction

    function! LightlineFugitive()
        if exists('*fugitive#head')
            let branch = fugitive#head()
            return branch !=# '' ? ''.branch : ''
        endif
        return ''
    endfunction

"" indentLine settings
    let g:indentLine_char = "│"
    let g:indentLine_faster = 1

"" FLY settings
    let g:FlyCscopeCase = 1

"" MuComplete settings
    set shortmess+=c   " Shut off completion messages
    set belloff+=ctrlg " If Vim beeps during completion
    set complete=.,w,b,u,k
    set completeopt+=menuone
    set completeopt+=noselect
    set completeopt+=noinsert
    set completeopt-=preview
    set noinfercase
    let g:mucomplete#enable_auto_at_startup = 1
    let g:mucomplete#chains = {}
    let g:mucomplete#chains.default = ['omni', 'c-n', 'path', 'tags', 'dict']
    let s:cpp_cond = { t -> t =~# '\%(->\|::\|\.\)$' }
    let g:mucomplete#can_complete = {}
    let g:mucomplete#can_complete.cpp = { 'omni': s:cpp_cond }

"" Tagbar settings
    let g:tagbar_width = 40
    let g:tagbar_indent = 1
    let g:tagbar_autoshowtag = 1
    let g:tagbar_foldlevel = 9
    let g:tagbar_sort = 0
    let g:tagbar_case_insensitive = 1
    let g:tagbar_singleclick = 1

"" LanguageClient settings
    let g:LanguageClient_settingsPath = '~/.config/nvim/langClient.json'
    let g:LanguageClient_serverCommands = {
        \ 'rust' : ['rustup', 'run', 'stable', 'rls'],
        \ 'c': ['ccls', '--log-file=/tmp/ccls.log'],
        \ 'cpp': ['ccls', '--log-file=/tmp/ccls.log'],
        \ }
    function! LC_maps()
      if has_key(g:LanguageClient_serverCommands, &filetype)
        set completefunc=LanguageClient#complete
        set formatexpr=LanguageClient#textDocument_rangeFormatting_sync()
        nnoremap <leader>ld :call LanguageClient#textDocument_definition()<CR>
        nnoremap <leader>lr :call LanguageClient#textDocument_rename()<CR>
        nnoremap <leader>lf :call LanguageClient#textDocument_formatting()<CR>
        nnoremap <leader>lt :call LanguageClient#textDocument_typeDefinition()<CR>
        nnoremap <leader>lx :call LanguageClient#textDocument_references()<CR>
        nnoremap <leader>la :call LanguageClient_workspace_applyEdit()<CR>
        nnoremap <leader>lc :call LanguageClient#textDocument_completion()<CR>
        nnoremap <leader>lh :call LanguageClient#textDocument_hover()<CR>
        nnoremap <leader>ls :call LanguageClient_textDocument_documentSymbol()<CR>
        nnoremap <leader>lm :call LanguageClient_contextMenu()<CR>
      endif
    endfunction
    autocmd FileType * call LC_maps()
