"" Initializations
	set nocompatible 				" No comatibility with old Vi
	set tabstop=4 					" Show a tabstop as 4 spaces
	set shiftwidth=4 				" Insert 4 spaces when Tab is pressed
	set number 						" Display line numbers
	set incsearch 					" Incremental Search
	set hlsearch 					" Highlight searches
	set cursorline 					" Horizontal line to indicate cursor
	set scrolloff=3 				" Number of lines to keep at the top and bottom of a window while scrolling
	set updatetime=500 				" Time interval to update windows
	set wildmenu 					" Pressing tab in command mode shows options on status bar
	" set mouse=a 					" Enable mouse to behave properly in vim
	set ruler 						" Display Ruler always.
	set laststatus=2				" Display Statusbar always.
	set hidden					" Hide closed buffers instead of closing them.
	syntax on 						" Enable syntax highlighting
	filetype on 					" Enable detecting filetype automatically
	filetype plugin on 				" Enable use of plugins for specific filetypes
	filetype plugin indent on 		" Enable Filetype indent plugin
	set ofu=syntaxcomplete#Complete " for omnicompletion
	set completeopt=longest,menuone " for omnicompletion
	let mapleader=";" 				" For setting the leader

"" Vim jumps to the last known position when reopening a file
	if has("autocmd")
		au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
					\| exe "normal! g'\"" | endif
	endif

"" PATHOGEN SETTINGS. Make sure to have pathogen installed.
	if !exists("g:loaded_pathogen")
		call pathogen#runtime_append_all_bundles()
		call pathogen#helptags()
	endif

"" Color Scheme Settings. Makesure peaksea.vim is present in colors directory
	if &diff
		" set t_Co=256
		set background=dark
		colorscheme peaksea
	else
		colorscheme  koehler
	endif

	inoremap jj <Esc>			"" press j twice instead of <ESC> in INSERT mode
	nnoremap j gj				" Go between lines in wrapped lines.
	nnoremap k gk				" Go between lines in wrapped lines.

"" Clear search results.
	nmap <leader>/ :set nohlsearch<CR>

"" To control fold behavior
	set foldmethod=indent
	set nofoldenable
	nmap \f :set foldnestmax=1<CR>
	nmap \F :set nofoldenable<CR>

"" To edit and apply .vimrc on the fly
	nmap \v :vnew ~/.vimrc<CR>
	if has("autocmd")
		autocmd! bufwritepost .vimrc source $MYVIMRC
	else
		nmap \\v :source ~/.vimrc<CR>
	endif

"" Maps Ctrl+[h,j,k,l] to move between window splits
	map <C-H> <C-w>h
	map <C-J> <C-w>j
	map <C-K> <C-w>k
	map <C-L> <C-w>l

"" Mapping to maximise the current horizontal split
	map <C-x> <C-w>_

"" Maps Ctrl+arrow keys to resize the window splits
	map <C-Up> <C-w>+ 
	map <C-Down> <C-W>-
	map <C-Left> <C-W><
	map <C-Right> <C-w>>

"" Mapping to close a buffer easily
	map <leader>q :q<CR>
	map <leader>x :x<CR>
	map <leader>w :w<CR>
	map <leader>Q :q!<CR>
	map <leader>X :x!<CR>
	map <leader>W :w!<CR>

"" Tags settings and mappings
	set tags=tags;

"" TagList Settings
	nmap <leader>6  :TlistToggle<CR>		" Open and close the taglist.vim separately
	let g:Tlist_Auto_Open = 1             	" always show the tag file
    let g:Tlist_Exit_OnlyWindow = 1		  	" If you are the last, kill yourself
    let g:Tlist_Enable_Fold_Column = 0	  	" Showing folding tree
	let g:Tlist_File_Fold_Auto_Close = 1  	" automatically fold hidden buffers
    let g:Tlist_Use_Right_Window = 1	  	" Split to the right side of the screen
    let g:Tlist_WinWidth = 33			  	" Set the window width
    let g:Tlist_Sort_Type = "order"		  	" Sort by the order
    let g:Tlist_Compact_Format = 1		  	" Do not display the help info
    let g:Tlist_File_Fold_Auto_Close = 1  	" Do not close tags for other files
    let g:Tlist_Show_One_File = 0         	" Always display one file tags

"" NERD_tree Settings
	nmap <leader>7 :NERDTreeToggle<CR> 		" Toggle NERDTree
    let g:NERDTreeWinSize = 33 				" Set the window width
    let g:NERDTreeWinPos = "left" 			" Set the window position
    let g:NERDTreeAutoCenter = 0 			" Auto centre
    let g:NERDTreeHighlightCursorline = 1 	" Highlight the cursor line

"" Source Explorer Settings
	nmap <leader>8 :SrcExplToggle<CR> 		" Open and close the srcexpl.vim separately

    "In order to Avoid conflicts, the Source Explorer should know what plugins
    "are using buffers. And you need add their bufname into the list below
    "according to the command ":buffers!"                                      
    let g:SrcExpl_pluginList = [
        \ "__Tag_List__",
        \ "_NERD_tree_",
        \ "Source_Explorer"
    \ ]

    let g:SrcExpl_winHeight = 12 			" Set the height of Source Explorer window
    let g:SrcExpl_refreshTime = 1 			" Set 100 ms for refreshing the Source Explorer
    let g:SrcExpl_jumpKey = "<ENTER>" 		" Set Enter key to jump into the exact definition context
    let g:SrcExpl_gobackKey = "<SPACE>" 	" Set Space key for back from the definition context
    let g:SrcExpl_searchLocalDef = 1 		" Enable/Disable the local definition searching
    "let g:SrcExpl_isUpdateTags = 0 		" Let the Source Explorer update the tags file when opening
    "let g:SrcExpl_updateTagsCmd = "ctags --sort=foldcase -R ."  " Use program 'ctags' with argument '--sort=foldcase -R' to create or update a tags file
    "let g:SrcExpl_updateTagsKey = "<F10>" 	" Set <F10> key for updating the tags file artificially                   

"" Enter the Matrix
	nmap <C-Space> :!vim +Matrix<CR>

"" Autotags Maps
	map <leader>au :call AutotagsUpdate()<CR>
	map <leader>aa :call AutotagsAdd()<CR>
	let g:autotags_pathhash_humanreadable = 1
